apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock-pfis-virtualservice1
spec:
  hosts:
    - "{{ .Values.virtualService.host1 }}"
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - name: mock-pfis-route
      route:
        - destination:
            host: mock-pfis
            port:
              number: 4000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock-pfis-virtualservice2
spec:
  hosts:
    - "{{ .Values.virtualService.host2 }}"
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - name: mock-pfis-route
      route:
        - destination:
            host: mock-pfis
            port:
              number: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock-pfis-virtualservice3
spec:
  hosts:
    - "{{ .Values.virtualService.host3 }}"
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - name: mock-pfis-route
      route:
        - destination:
            host: mock-pfis
            port:
              number: 8000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock-pfis-virtualservice4
spec:
  hosts:
    - "{{ .Values.virtualService.host4 }}"
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - name: mock-pfis-route
      route:
        - destination:
            host: mock-pfis
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mock-pfis-virtualservice5
spec:
  hosts:
    - "{{ .Values.virtualService.host5 }}"
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - name: mock-pfis-route
      route:
        - destination:
            host: mock-pfis
            port:
              number: 9000

---
# this lets app receive traffic from common ingress gateway
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: mock-pfis-host
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        hosts:
        - "{{ .Values.virtualService.host1 }}"
        - "{{ .Values.virtualService.host2 }}"
        - "{{ .Values.virtualService.host3 }}"
        - "{{ .Values.virtualService.host4 }}"
        - "{{ .Values.virtualService.host5 }}"
  - from:
    - source:
        namespaces: ["istio-system"]
